(ns fuchi.methods.test-displacement-scorecard
  (:require [clojure.test :refer [deftest is]]
            [clojure.string :as str]
            [fuchi.methods.displacement-scorecard :as sc]
            [fuchi.methods.public-person :as pp]
            #?(:clj [fuchi.methods.displacement-l0-path :as dl0])
            #?(:clj [clojure.java.io :as io])))

(deftest test-live-refuse-matrix
  (let [legs (sc/live-refuse-matrix)]
    (is (seq legs))
    (is (every? #(false? (:admissible %)) legs))
    (is (every? #(= 0 (:cash-usd-micros %)) legs))))

#?(:clj
   (deftest test-build-scorecard
     (let [body (sc/build)]
       (is (false? (:scorecard/live body)))
       (is (= 0 (:scorecard/cash-usd-micros body)))
       (is (= [] (:scorecard/score-surface body)))
       (is (true? (:scorecard/all-live-refused body)))
       (is (pos? (:scorecard/admissible-cohorts body)))
       (is (pos? (:scorecard/refused-cohorts body)))
       (is (pos? (:scorecard/enrolled-subjects body)))
       (is (pos? (:scorecard/committed-usd-micros-yr body)))
       (is (pos? (:scorecard/booked-entries body)))
       (is (pos? (:scorecard/tenure-subjects body)))
       (is (pos? (:scorecard/tenure-admissible-cohorts body)))
       (is (= "L6" (or (ffirst (:scorecard/tenure-stage-counts body))
                       (some-> (:scorecard/tenure-stage-counts body) keys first))))
       (is (pos? (:scorecard/gov-flowable-committed-usd-micros body)))
       (is (pos? (:scorecard/tenure-gov-flowable-committed-usd-micros body)))
       (is (pos? (:scorecard/tenure-gov-post-ratify-committed-usd-micros body)))
       (is (< (:scorecard/tenure-gov-flowable-committed-usd-micros body)
              (:scorecard/tenure-gov-post-ratify-committed-usd-micros body)))
       (is (pos? (:scorecard/tenure-disclosure-open body)))
       (is (zero? (:scorecard/tenure-disclosure-held body)))
       (is (pos? (:scorecard/mitsuho-r1-dry body)))
       (is (pos? (:scorecard/mitsuho-gated-refused body)))
       (is (zero? (:scorecard/mitsuho-produce-executed body)))
       (is (pos? (:scorecard/hikari-r1-dry body)))
       (is (pos? (:scorecard/hikari-gated-refused body)))
       (is (zero? (:scorecard/hikari-generate-executed body)))
       (is (pos? (:scorecard/care-r1-dry body)))
       (is (pos? (:scorecard/care-gated-refused body)))
       (is (zero? (:scorecard/care-delivery-executed body)))
       (is (pos? (:scorecard/housing-r1-dry body)))
       (is (pos? (:scorecard/housing-gated-refused body)))
       (is (zero? (:scorecard/housing-land-grant-executed body)))
       (is (pos? (:scorecard/housing-council-held body)))
       (is (pos? (:scorecard/tooling-r1-dry body)))
       (is (pos? (:scorecard/tooling-gated-refused body)))
       (is (zero? (:scorecard/tooling-fulfillment-executed body)))
       (is (pos? (:scorecard/compute-r1-dry body)))
       (is (pos? (:scorecard/compute-gated-refused body)))
       (is (zero? (:scorecard/compute-quota-executed body)))
       (is (pos? (:scorecard/liquidity-r1-dry body)))
       (is (pos? (:scorecard/liquidity-gated-refused body)))
       (is (zero? (:scorecard/liquidity-loan-executed body)))
       (is (pos? (:scorecard/liquidity-member-principal body)))
       (is (zero? (:scorecard/liquidity-cash-usd-micros body)))
       ;; R2 execute membrane (default refuse; never side-effects)
       (is (pos? (:scorecard/r2-status-count body)))
       (is (pos? (:scorecard/r2-refused body)))
       (is (zero? (:scorecard/r2-executed body)))
       (is (true? (:scorecard/all-r2-not-executed body)))
       (is (map? (:scorecard/r2-by-rail body)))
       (is (pos? (get-in body [:scorecard/r2-by-rail "food"] 0)))
       (let [sp (:scorecard/ss-priority-path body)]
         (is (map? sp))
         (is (nil? (:error sp)))
         (is (= "L0" (:l0-stage sp)))
         (is (false? (:l0-published sp)))
         (is (= "L4" (:ladder-to sp)))
         (is (= "care" (:ladder-rails-hint-first sp)))
         (is (false? (:ladder-published sp)))
         (is (true? (:held-stress-ladder-refused sp)))
         (is (= "L4" (:stage-sustenance-stage sp)))
         (is (= "care" (:stage-rails-first sp)))
         (is (= "housing" (:stage-rails-second sp)))
         (is (pos? (:stage-care-hours-floor-yr sp)))
         (is (false? (:stage-land-grant-executed sp)))
         (is (true? (:stage-r2-all-refused sp)))
         (is (= "open" (:disclosure-state sp)))
         (is (true? (:entitlements-may-flow? sp)))
         (is (true? (:held-stress-held? sp)))
         (is (= 7 (:rails-gated-count sp)))
         (is (zero? (:rails-gated-admissible-count sp)))
         (is (true? (:all-rails-gated-refused sp)))
         (is (= 7 (:r2-status-count sp)))
         (is (zero? (:r2-executed-count sp)))
         (is (true? (:all-r2-not-executed sp)))
         (is (false? (:housing-land-grant-executed sp)))
         (is (false? (:live sp)))
         (is (zero? (:cash-usd-micros sp))))
       (is (map? (:scorecard/all-held-stress body)))
       (is (zero? (get-in body [:scorecard/all-held-stress :gov-flowable])))
       (is (pos? (get-in body [:scorecard/all-held-stress :open-gov-flowable])))
       (is (pos? (get-in body [:scorecard/all-held-stress :held-subjects])))
       (is (false? (get-in body [:scorecard/all-held-stress :live])))
       (is (= pp/PRIORITY-STACK (:scorecard/priority-stack body)))
       (let [md (sc/scorecard-md body)]
         (is (str/includes? md "scorecard"))
         (is (str/includes? md "wellbecoming"))
         (is (str/includes? md "tenure"))
         (is (str/includes? md "tenure gov flowable"))
         (is (str/includes? md "disclosure open/held"))
         (is (str/includes? md "mitsuho food"))
         (is (str/includes? md "hikari energy"))
         (is (str/includes? md "care-iyashi"))
         (is (str/includes? md "housing-commons"))
         (is (str/includes? md "tooling-okaimono"))
         (is (str/includes? md "compute-murakumo"))
         (is (str/includes? md "liquidity-warifu"))
         (is (str/includes? md "R2 execute membrane"))
         (is (str/includes? md "all-r2-not-executed"))
         (is (str/includes? md "SS priority path"))
         (is (str/includes? md "ladder offline:"))
         (is (str/includes? md "rails-hint-first="))
         (is (str/includes? md "stage_sustenance:"))
         (is (str/includes? md "r2-all-refused="))
         (is (str/includes? md "all-rails-gated-refused"))
         (is (str/includes? md "member-principal"))
         (is (str/includes? md "All-disclosure-held stress"))
         (is (str/includes? md "land-grant-executed"))
         (is (str/includes? md "all live legs refused"))
         (is (not (str/includes? md "| rank |")))))))

#?(:clj
   (deftest test-build-from-bare-l0-batch-attaches-tenure
     (let [bare (dl0/run-default-seed :max-slots 2 :climb-steps 4)
           body (sc/build bare)]
       (is (nil? (some :tenure-phase (:packages bare))))
       (is (pos? (:scorecard/tenure-subjects body)))
       (is (pos? (:scorecard/tenure-admissible-cohorts body)))
       (is (pos? (:scorecard/tenure-gov-flowable-committed-usd-micros body)))
       (is (false? (:scorecard/live body)))
       (is (= 0 (:scorecard/cash-usd-micros body))))))

#?(:clj
   (deftest test-write-scorecard
     (let [paths (sc/write-scorecard!)]
       (is (.exists (io/file (:md paths))))
       (is (.exists (io/file (:edn paths))))
       (is (true? (:all-live-refused paths)))
       (is (false? (:live paths)))
       (is (pos? (:tenure-subjects paths)))
       (is (str/includes? (slurp (:md paths)) "No personal scores")))))
